import type { Event, Organization, Profile, Campus } from "./types";

// Fallback fixtures used while Supabase env vars aren't wired up. Real data replaces
// these the moment NEXT_PUBLIC_SUPABASE_URL points at a real project.

export const mockCampus: Campus = {
  id: "ucsd",
  name: "UC San Diego",
  slug: "ucsd",
  city: "La Jolla",
  country: "USA",
  center_lat: 32.8812,
  center_lng: -117.2374,
  accent_hex: "#FFD60A",
};

export const mockEvents: Event[] = [
  {
    id: "warren-quad-1",
    title: "Warren Quad Takeover",
    summary: "DJ set, food trucks, glow sticks. Outdoor. 18+.",
    starts_at: new Date(Date.now() + 2 * 3600_000).toISOString(),
    ends_at: new Date(Date.now() + 6 * 3600_000).toISOString(),
    location_name: "Warren Quad, UCSD",
    latitude: 32.8824,
    longitude: -117.2355,
    host_name: "Warren College Council",
    host_handle: "warren-council",
    category: "party",
    is_live: false,
    attendee_count: 312,
    tags: ["outdoor", "dj", "18+"],
  },
  {
    id: "acm-boba",
    title: "ACM Boba Night",
    summary: "Free boba and chill vibes with the computing community. First 50.",
    starts_at: new Date(Date.now() + 45 * 60_000).toISOString(),
    ends_at: new Date(Date.now() + 3 * 3600_000).toISOString(),
    location_name: "CSE Building Lobby",
    latitude: 32.8811,
    longitude: -117.2336,
    host_name: "ACM @ UCSD",
    host_handle: "acm-ucsd",
    category: "free_food",
    is_live: true,
    attendee_count: 47,
    tags: ["free-food", "cs", "boba"],
  },
  {
    id: "greek-rush-fiji",
    title: "FIJI Rush — Beach Day",
    summary: "Round 2 rush event. Transportation provided from Price Center.",
    starts_at: new Date(Date.now() + 26 * 3600_000).toISOString(),
    location_name: "La Jolla Shores",
    latitude: 32.8563,
    longitude: -117.2568,
    host_name: "Phi Gamma Delta",
    host_handle: "fiji",
    category: "greek",
    attendee_count: 89,
    tags: ["rush", "beach"],
  },
  {
    id: "startup-career-fair",
    title: "Startup Career Fair",
    summary: "45 startups, free food, OCE-sponsored. Bring your resume.",
    starts_at: new Date(Date.now() + 48 * 3600_000).toISOString(),
    location_name: "Price Center West Ballroom",
    latitude: 32.8795,
    longitude: -117.2369,
    host_name: "Office of Career Engagement",
    host_handle: "oce",
    category: "career",
    attendee_count: 540,
    tags: ["career", "startups", "free-food"],
  },
  {
    id: "triton-basketball",
    title: "Triton Basketball vs. UC Irvine",
    summary: "Big West conference home game. Student section opens 6pm.",
    starts_at: new Date(Date.now() + 72 * 3600_000).toISOString(),
    location_name: "LionTree Arena",
    latitude: 32.8858,
    longitude: -117.2429,
    host_name: "UCSD Athletics",
    host_handle: "ucsd-athletics",
    category: "sports",
    attendee_count: 1250,
    tags: ["basketball", "big-west"],
  },
  {
    id: "ai-seminar",
    title: "Prof. Ng on LLM Agents",
    summary: "Public research talk — no ticket needed. Q&A after.",
    starts_at: new Date(Date.now() + 4 * 3600_000).toISOString(),
    location_name: "CSE 1202",
    latitude: 32.8812,
    longitude: -117.2338,
    host_name: "CSE Department",
    host_handle: "cse",
    category: "academic",
    attendee_count: 132,
    tags: ["research", "ai"],
  },
];

export const mockOrgs: Organization[] = [
  {
    id: "acm-ucsd",
    handle: "acm-ucsd",
    name: "ACM @ UCSD",
    tagline: "Build. Ship. Hack.",
    description:
      "The Association for Computing Machinery chapter at UCSD. 2,800 members. Weekly hack nights, industry talks, mentorship, and the annual DiamondHacks hackathon.",
    member_count: 2831,
    accent_hex: "#FFD60A",
    category: "Academic / Tech",
    campus: "ucsd",
    verified: true,
    instagram_handle: "acmucsd",
    website_url: "https://acmucsd.com",
  },
  {
    id: "fiji",
    handle: "fiji",
    name: "Phi Gamma Delta",
    tagline: "Building better men since 1848.",
    description:
      "Social fraternity. Fall rush starts Week 2. Philanthropy partners with the American Red Cross.",
    member_count: 84,
    accent_hex: "#6F4BE8",
    category: "Greek Life",
    campus: "ucsd",
    verified: true,
    instagram_handle: "fiji.ucsd",
    website_url: "https://phigam.org",
  },
  {
    id: "warren-council",
    handle: "warren-council",
    name: "Warren College Council",
    tagline: "Your college, your voice.",
    description:
      "Student government for Earl Warren College. Organizes Quadstock, Warren Live, and weekly college-wide events.",
    member_count: 412,
    accent_hex: "#FF2D92",
    category: "Student Government",
    campus: "ucsd",
    verified: true,
    instagram_handle: "warrencollegeucsd",
    website_url: "https://warren.ucsd.edu",
  },
];

export const mockProfile: Profile = {
  id: "you",
  handle: "you",
  display_name: "Guest",
  bio: "Exploring Buzz. Sign in to make it yours.",
  campus: "ucsd",
  streak: 0,
  events_attended: 0,
};
